# Generated by Django 5.0.7 on 2025-01-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments_bids_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='image',
            new_name='image_url',
        ),
    ]
