# Generated by Django 5.0.7 on 2025-01-06 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_image_listings_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listings'),
        ),
    ]
